#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=192:00:00,mem=96gb
#PBS -N assemble_mito4
#PBS -M aps216@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

REF_READS="/storage/home/aps216/scratch/Conch/data/RefAssembly/ref4/"

working_dir=$PBS_O_WORKDIR

# ------------------------------------------------------------------------------
# Assemble mitochondrial genome with norgal
# ------------------------------------------------------------------------------

cd $working_dir

module load python/3.6.3-anaconda5.0.1; python /storage/home/aps216/work/norgal/norgal.py -i ${REF_READS}/Cayo_Agua_2-3_S1_kraken4_TRIM_R1.rmdup.fastq ${REF_READS}/Cayo_Agua_2-3_S1_kraken4_TRIM_R2.rmdup.fastq -t 8 -o ${REF_READS}/norgal_output4_noNuc --blast

exit;

