#!/bin/bash

#PBS -l nodes=1:ppn=12,walltime=4:00:00,mem=96gb
#PBS -N assess-ref0
#PBS -M aps216@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

REF_READS="/storage/home/aps216/scratch/Conch/genomes/nuclear/Cayo_Agua_2-3_S1"

working_dir=$PBS_O_WORKDIR

cd $working_dir

# ========================================================================================
# --- Assess reference assembly quality
# ========================================================================================

IND=Cayo_Agua_2-3_S1

echo "Assessing assembly quality began at [`date`]" >> $IND.assembly.log

module load quast/4.6.0

#Cayo_Agua_2-3_S1.scafSeq

# Run without reference
SCAF=${REF_READS}/${IND}.scafSeq

module load python/3.6.3-anaconda5.0.1; python $QUAST_DIR/quast.py \
    ${SCAF} \
    --scaffolds \
    --threads 24 \
    -o ${REF_READS}/Cayo_Agua_2-3_S1-quast_results_noref_gf \
    -L --eukaryote \
    --gene-finding

echo "Assessing assembly quality ended at [`date`]" >> $IND.assembly.log

exit;

