#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -N index_ref4
#PBS -M aps216@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

REF_KRAKEN4="/storage/home/aps216/scratch/Conch/genomes/nuclear/Cayo_Agua_2-3_S1_kraken4"

working_dir=$PBS_O_WORKDIR

# ------------------------------------------------------------------------------
# Index reference assembly V4
# ------------------------------------------------------------------------------

cd $working_dir

module load bwa; bwa index ${REF_KRAKEN4}/Cayo_Agua_2-3_S1_kraken4.scafSeq-gt500.fa

module load picard; java -Xmx24g -jar $PICARD/picard.jar CreateSequenceDictionary REFERENCE=${REF_KRAKEN4}/Cayo_Agua_2-3_S1_kraken4.scafSeq-gt500.fa OUTPUT=${REF_KRAKEN4}/Cayo_Agua_2-3_S1_kraken4.scafSeq-gt500.dict

samtools faidx ${REF_KRAKEN4}/Cayo_Agua_2-3_S1_kraken4.scafSeq-gt500.fa

exit;

