#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -N index_refs
#PBS -M aps216@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

REF_DIR=$(echo "/storage/home/aps216/scratch/Conch/ref_genome")

working_dir=$PBS_O_WORKDIR

# ------------------------------------------------------------------------------
# Index reference assemblies
# ------------------------------------------------------------------------------

cd $working_dir

module load bwa; bwa index ${REF_DIR}/Cayo_Agua_2-3_S1.scafSeq.fa

module load picard; java -Xmx24g -jar $PICARD/picard.jar CreateSequenceDictionary REFERENCE=${REF_DIR}/Cayo_Agua_2-3_S1.scafSeq.fa OUTPUT=${REF_DIR}/Cayo_Agua_2-3_S1.scafSeq.dict

samtools faidx ${REF_DIR}/Cayo_Agua_2-3_S1.scafSeq.fa

exit;

