#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=12:00:00
#PBS -N trim-ref-seqs
#PBS -M aps216@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

REF_READS="/storage/home/aps216/scratch/Conch/data/RefAssembly"

working_dir=$PBS_O_WORKDIR

# ------------------------------------------------------------------------------
# Trim sequences
# ------------------------------------------------------------------------------

cd $working_dir

#Cayo_Agua_2-3_S1_R1.fastq.gz

IND=Cayo_Agua_2-3_S1

echo "Trimming for individual $IND";

module load trimmomatic/0.36

ADAPTERS=`dirname $TRIMMOMATIC`/adapters/TruSeq2-PE.fa

java -jar $TRIMMOMATIC PE -phred33 \
    -threads 8 \
    ${REF_READS}/${IND}_R1.fastq.gz \
    ${REF_READS}/${IND}_R2.fastq.gz \
    ${REF_READS}/${IND}_TRIM_R1.fastq.gz \
    ${REF_READS}/${IND}_trim_unpaired_R1.fastq.gz \
    ${REF_READS}/${IND}_TRIM_R2.fastq.gz \
    ${REF_READS}/${IND}_trim_unpaired_R2.fastq.gz \
    ILLUMINACLIP:$ADAPTERS:2:30:10 \
    LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

exit;

